odu100_table_model = {
    '7.2.20': {'eswATUConfigTable': ['eswATUConfigAtuId',
                                     'eswATUConfigEntryType',
                                     'eswATUConfigPriorityVal',
                                     'eswATUConfigMacAddress',
                                     'eswATUConfigMemberPorts',
                                     'eswATUConfigRowStatus'],
               'eswBadFramesTable': ['eswBadFramesInUndersizeRx',
                                     'eswBadFramesInFragmentsRx',
                                     'eswBadFramesInOversizeRx',
                                     'eswBadFramesInJabberRx',
                                     'eswBadFramesInFCSErrRx',
                                     'eswBadFramesOutFCSErrTx',
                                     'eswBadFramesDeferredTx',
                                     'eswBadFramesCollisionsTx',
                                     'eswBadFramesLateTx',
                                     'eswBadFramesExcessiveTx',
                                     'eswBadFramesSingleTx',
                                     'eswBadFramesMultipleTx'],
               'eswGoodFramesTable': ['eswGoodFramesInUnicast',
                                      'eswGoodFramesOutUnicast',
                                      'eswGoodFramesInBCast',
                                      'eswGoodFramesOutBCast',
                                      'eswGoodFramesInMCast',
                                      'eswGoodFramesOutMcast'],
               'eswMirroringPortTable': ['eswMirroringPort', 'eswMirroringPortSecond'],
               'eswPortAccessListTable': ['eswPortACLSecIndex', 'eswPortACLMacAddress'],
               'eswPortBwTable': ['eswPortBwEgressBw', 'eswPortBwIngressBw'],
               'eswPortConfigTable': ['eswPortConfigPortNum',
                                      'eswPortConfigAdminState',
                                      'eswPortConfigLinkMode',
                                      'eswPortConfigPortVid',
                                      'eswPortConfigAuthState',
                                      'eswPortConfigMirrDir',
                                      'eswPortConfigDotqMode',
                                      'eswPortConfigMacFlowControl'],
               'eswPortQinQTable': ['eswPortQinQAuthState', 'eswPortQinQProviderTag'],
               'eswPortStatisticsTable': ['eswPortStatisticsInDiscards',
                                          'eswPortStatisticsInGoodOctets',
                                          'eswPortStatisticsInBadOctets',
                                          'eswPortStatisticsOutOctets'],
               'eswPortStatusTable': ['eswPortStatusOpState',
                                      'eswPortStatusLinkSpeed',
                                      'eswPortStatusMacFlowControl'],
               'eswVlanConfigTable': ['eswVlanConfigVlanId',
                                      'eswVlanConfigVlanName',
                                      'eswVlanConfigVlanType',
                                      'eswVlanConfigVlanTag',
                                      'eswVlanConfigMemberPorts',
                                      'eswVlanConfigRowStatus'],
               'hwDescTable': ['hwDescIndex', 'hwVersion', 'hwSerialNo'],
               'ipConfigTable': ['ipConfigIndex',
                                 'adminState',
                                 'ipAddress',
                                 'ipNetworkMask',
                                 'ipDefaultGateway',
                                 'autoIpConfig',
                                 'managementMode',
                                 'managementVlanTag'],
               'nwInterfaceStatisticsTable': ['nwStatsIndex',
                                              'rxPackets',
                                              'txPackets',
                                              'rxBytes',
                                              'txBytes',
                                              'rxErrors',
                                              'txErrors',
                                              'rxDropped',
                                              'txDropped'],
               'nwInterfaceStatusTable': ['nwStatusIndex',
                                          'nwInterfaceName',
                                          'operationalState',
                                          'macAddress'],
               'omcConfTable': ['omcConfIndex', 'omcIpAddress', 'periodicStatsTimer'],
               'peerConfigTable': ['timeslotIndex',
                                   'peerMacAddress',
                                   'guaranteedUplinkBW',
                                   'guaranteedDownlinkBW',
                                   'basicRateMCSIndex',
                                   'maxUplinkBW',
                                   'maxDownlinkBW'],
               'peerLinkStatisticsTable': ['timeslotindex',
                                           'txdroped',
                                           'rxDataSubFrames',
                                           'txDataSubFrames',
                                           'signalstrength1',
                                           'txRetransmissions5',
                                           'txRetransmissions4',
                                           'txRetransmissions3',
                                           'txRetransmissions2',
                                           'txRetransmissions1',
                                           'txRetransmissions0',
                                           'rxRetransmissions5',
                                           'rxRetransmissions4',
                                           'rxRetransmissions3',
                                           'rxRetransmissions2',
                                           'rxRetransmissions1',
                                           'rxRetransmissions0',
                                           'rxBroadcastDataSubFrames',
                                           'rateIncreases',
                                           'rateDecreases',
                                           'emptyRasters',
                                           'rxDroppedTpPkts',
                                           'rxDroppedRadioPkts',
                                           'signalstrength2'],
               'peerNodeStatusTable': ['timeSlotIndex',
                                       'linkStatus',
                                       'tunnelStatus',
                                       'sigStrength1',
                                       'peerMacAddr',
                                       'ssIdentifier',
                                       'peerNodeStatusNumSlaves',
                                       'peerNodeStatusrxRate',
                                       'peerNodeStatustxRate',
                                       'allocatedTxBW',
                                       'allocatedRxBW',
                                       'usedTxBW',
                                       'usedRxBW',
                                       'txbasicRate',
                                       'sigStrength2',
                                       'rxbasicRate',
                                       'txLinkQuality',
                                       'peerNodeStatustxTime',
                                       'peerNodeStatusrxTime',
                                       'negotiatedMaxUplinkBW',
                                       'negotiatedMaxDownlinkBW',
                                       'peerNodeStatuslinkDistance'],
               'peerRateStatisticsTable': ['timeSlotindex',
                                           'mcsIndex',
                                           'peerrate',
                                           'per',
                                           'ticks',
                                           'ticksMinimumRateTx',
                                           'ticksWasted'],
               'peerTunnelStatisticsTable': ['tsIndex',
                                             'rxPacket',
                                             'txPacket',
                                             'rxBundles',
                                             'txBundles',
                                             'rxDroped',
                                             'txDroped'],
               'raAclConfigTable': ['aclIndex', 'macaddress', 'rowSts'],
               'raChannelListTable': ['raChanIndex', 'channelNumber', 'frequency'],
               'raConfTable': ['raIndex',
                               'raAdminState',
                               'aclMode',
                               'ssID',
                               'guaranteedBroadcastBW',
                               'dba',
                               'acm',
                               'acs',
                               'dfs',
                               'numSlaves',
                               'antennaPort',
                               'linkDistance'],
               'raLlcConfTable': ['arqWinLow',
                                  'arqWinHigh',
                                  'frameLossThreshold',
                                  'leakyBucketTimerVal',
                                  'frameLossTimeout'],
               'raPreferredRFChannelTable': ['preindex', 'preindex', 'rafrequency'],
               'raScanListTable': ['raScanIndex',
                                   'ssid',
                                   'signalStrength',
                                   'macAddr',
                                   'rastertime',
                                   'timeslot',
                                   'maxSlaves',
                                   'channelNum',
                                   'basicRate',
                                   'radfs',
                                   'raacm'],
               'raSiteSurveyResultTable': ['scanIndex',
                                           'scanIndex',
                                           'rfChannelFrequency',
                                           'numCrcErrors',
                                           'maxRslCrcError',
                                           'numPhyErrors',
                                           'maxRslPhyError',
                                           'maxRslValidFrames',
                                           'channelnumber',
                                           'noiseFloor'],
               'raStatusTable': ['currentTimeSlot',
                                 'raMacAddress',
                                 'raoperationalState',
                                 'unusedTxTimeUL',
                                 'unusedTxTimeDL'],
               'raTddMacConfigTable': ['passPhrase',
                                       'txPower',
                                       'maxPower',
                                       'maxCrcErrors',
                                       'leakyBucketTimerValue',
                                       'encryptionType'],
               'raTddMacStatisticsTable': ['rxpackets',
                                           'txpackets',
                                           'rxerrors',
                                           'txerrors',
                                           'rxdropped',
                                           'txdropped',
                                           'rxCrcErrors',
                                           'rxPhyError'],
               'raTddMacStatusTable': ['rfChanFreq'],
               'raValidPhyRatesTable': ['mcsindex',
                                        'spatialStreams',
                                        'modulationType',
                                        'codingRate',
                                        'rate'],
               'ruConfTable': ['confIndex',
                               'adminstate',
                               'defaultNodeType',
                               'channelBandwidth',
                               'synchSource',
                               'countryCode',
                               'poeState',
                               'alignmentControl'],
               'ruDateTimeTable': ['dateIndex',
                                   'year',
                                   'month',
                                   'day',
                                   'hour',
                                   'min',
                                   'sec'],
               'ruOmOperationsTable': ['omIndex',
                                       'omOperationReq',
                                       'userName',
                                       'password',
                                       'ftpServerAddress',
                                       'pathName',
                                       'omOperationResult',
                                       'omSpecificCause',
                                       'listOfChannels',
                                       'txTime',
                                       'txRate',
                                       'txBW'],
               'ruStatusTable': ['statusIndex',
                                 'lastRebootReason',
                                 'isConfigCommitedToFlash',
                                 'upTime',
                                 'poeStatus',
                                 'cpuId',
                                 'ruoperationalState',
                                 'nodeBandwidth'],
               'swStatusTable': ['swStatusIndex',
                                 'activeVersion',
                                 'passiveVersion',
                                 'bootloaderVersion'],
               'syncConfigTable': ['syncConfigIndex',
                                   'adminStatus',
                                   'synchState',
                                   'rasterTime',
                                   'syncLossThreshold',
                                   'leakyBucketTimer',
                                   'syncLostTimeout',
                                   'syncConfigTimerAdjust',
                                   'percentageDownlinkTransmitTime'],
               'synchStatisticsTable': ['syncLostCounter'],
               'synchStatusTable': ['syncoperationalState',
                                    'syncrasterTime',
                                    'timerAdjust',
                                    'syncpercentageDownlinkTransmitTime'],
               'sysOmcRegistrationTable': ['sysOmcRegistrationIndex',
                                           'sysOmcRegisterContactAddr',
                                           'sysOmcRegisterContactPerson',
                                           'sysOmcRegisterContactMobile',
                                           'sysOmcRegisterAlternateContact',
                                           'sysOmcRegisterContactEmail']
    },

    '7.2.25': {'eswATUConfigTable': ['eswATUConfigAtuId',
                                     'eswATUConfigEntryType',
                                     'eswATUConfigPriorityVal',
                                     'eswATUConfigMacAddress',
                                     'eswATUConfigMemberPorts',
                                     'eswATUConfigRowStatus'],
               'eswBadFramesTable': ['eswBadFramesInUndersizeRx',
                                     'eswBadFramesInFragmentsRx',
                                     'eswBadFramesInOversizeRx',
                                     'eswBadFramesInJabberRx',
                                     'eswBadFramesInFCSErrRx',
                                     'eswBadFramesOutFCSErrTx',
                                     'eswBadFramesDeferredTx',
                                     'eswBadFramesCollisionsTx',
                                     'eswBadFramesLateTx',
                                     'eswBadFramesExcessiveTx',
                                     'eswBadFramesSingleTx',
                                     'eswBadFramesMultipleTx'],
               'eswGoodFramesTable': ['eswGoodFramesInUnicast',
                                      'eswGoodFramesOutUnicast',
                                      'eswGoodFramesInBCast',
                                      'eswGoodFramesOutBCast',
                                      'eswGoodFramesInMCast',
                                      'eswGoodFramesOutMcast'],
               'eswMirroringPortTable': ['eswMirroringPort', 'eswMirroringPortSecond'],
               'eswPortAccessListTable': ['eswPortACLSecIndex', 'eswPortACLMacAddress'],
               'eswPortBwTable': ['eswPortBwEgressBw', 'eswPortBwIngressBw'],
               'eswPortConfigTable': ['eswPortConfigPortNum',
                                      'eswPortConfigAdminState',
                                      'eswPortConfigLinkMode',
                                      'eswPortConfigPortVid',
                                      'eswPortConfigAuthState',
                                      'eswPortConfigMirrDir',
                                      'eswPortConfigDotqMode',
                                      'eswPortConfigMacFlowControl'],
               'eswPortQinQTable': ['eswPortQinQAuthState', 'eswPortQinQProviderTag'],
               'eswPortStatisticsTable': ['eswPortStatisticsInDiscards',
                                          'eswPortStatisticsInGoodOctets',
                                          'eswPortStatisticsInBadOctets',
                                          'eswPortStatisticsOutOctets'],
               'eswPortStatusTable': ['eswPortStatusOpState',
                                      'eswPortStatusLinkSpeed',
                                      'eswPortStatusMacFlowControl'],
               'eswVlanConfigTable': ['eswVlanConfigVlanId',
                                      'eswVlanConfigVlanName',
                                      'eswVlanConfigVlanType',
                                      'eswVlanConfigVlanTag',
                                      'eswVlanConfigMemberPorts',
                                      'eswVlanConfigRowStatus'],
               'hwDescTable': ['hwDescIndex', 'hwVersion', 'hwSerialNo'],
               'ipConfigTable': ['ipConfigIndex',
                                 'adminState',
                                 'ipAddress',
                                 'ipNetworkMask',
                                 'ipDefaultGateway',
                                 'autoIpConfig',
                                 'managementMode',
                                 'managementVlanTag'],
               'ipFilterTable': ['ipFilterIndex',
                                 'ipFilterIpAddress',
                                 'ipFilterNetworkMask'],
               'macFilterTable': ['macFilterIndex', 'filterMacAddress'],
               'nwInterfaceStatisticsTable': ['nwStatsIndex',
                                              'rxPackets',
                                              'txPackets',
                                              'rxBytes',
                                              'txBytes',
                                              'rxErrors',
                                              'txErrors',
                                              'rxDropped',
                                              'txDropped'],
               'nwInterfaceStatusTable': ['nwStatusIndex',
                                          'nwInterfaceName',
                                          'operationalState',
                                          'macAddress'],
               'omcConfTable': ['omcConfIndex', 'omcIpAddress', 'periodicStatsTimer'],
               'peerConfigTable': ['timeslotIndex',
                                   'peerMacAddress',
                                   'guaranteedUplinkBW',
                                   'guaranteedDownlinkBW',
                                   'basicRateMCSIndex',
                                   'maxUplinkBW',
                                   'maxDownlinkBW'],
               'peerLinkStatisticsTable': ['timeslotindex',
                                           'txdroped',
                                           'rxDataSubFrames',
                                           'txDataSubFrames',
                                           'signalstrength1',
                                           'txRetransmissions5',
                                           'txRetransmissions4',
                                           'txRetransmissions3',
                                           'txRetransmissions2',
                                           'txRetransmissions1',
                                           'txRetransmissions0',
                                           'rxRetransmissions5',
                                           'rxRetransmissions4',
                                           'rxRetransmissions3',
                                           'rxRetransmissions2',
                                           'rxRetransmissions1',
                                           'rxRetransmissions0',
                                           'rxBroadcastDataSubFrames',
                                           'rateIncreases',
                                           'rateDecreases',
                                           'emptyRasters',
                                           'rxDroppedTpPkts',
                                           'rxDroppedRadioPkts',
                                           'signalstrength2'],
               'peerNodeStatusTable': ['timeSlotIndex',
                                       'linkStatus',
                                       'tunnelStatus',
                                       'sigStrength1',
                                       'peerMacAddr',
                                       'ssIdentifier',
                                       'peerNodeStatusNumSlaves',
                                       'peerNodeStatusrxRate',
                                       'peerNodeStatustxRate',
                                       'allocatedTxBW',
                                       'allocatedRxBW',
                                       'usedTxBW',
                                       'usedRxBW',
                                       'txbasicRate',
                                       'sigStrength2',
                                       'rxbasicRate',
                                       'txLinkQuality',
                                       'peerNodeStatustxTime',
                                       'peerNodeStatusrxTime',
                                       'negotiatedMaxUplinkBW',
                                       'negotiatedMaxDownlinkBW',
                                       'peerNodeStatuslinkDistance'],
               'peerRateStatisticsTable': ['timeSlotindex',
                                           'mcsIndex',
                                           'peerrate',
                                           'per',
                                           'ticks',
                                           'ticksMinimumRateTx',
                                           'ticksWasted'],
               'peerTunnelStatisticsTable': ['tsIndex',
                                             'rxPacket',
                                             'txPacket',
                                             'rxBundles',
                                             'txBundles',
                                             'rxDroped',
                                             'txDroped'],
               'raAclConfigTable': ['aclIndex', 'macaddress', 'rowSts'],
               'raChannelListTable': ['raChanIndex', 'channelNumber', 'frequency'],
               'raConfTable': ['raIndex',
                               'raAdminState',
                               'aclMode',
                               'ssID',
                               'guaranteedBroadcastBW',
                               'dba',
                               'acm',
                               'acs',
                               'dfs',
                               'numSlaves',
                               'antennaPort',
                               'linkDistance',
                               'anc'],
               'raLlcConfTable': ['arqWinLow',
                                  'arqWinHigh',
                                  'frameLossThreshold',
                                  'leakyBucketTimerVal',
                                  'frameLossTimeout'],
               'raPreferredRFChannelTable': ['preindex', 'preindex', 'rafrequency'],
               'raScanListTable': ['raScanIndex',
                                   'ssid',
                                   'signalStrength',
                                   'macAddr',
                                   'rastertime',
                                   'timeslot',
                                   'maxSlaves',
                                   'channelNum',
                                   'basicRate',
                                   'radfs',
                                   'raacm',
                                   'raanc'],
               'raSiteSurveyResultTable': ['scanIndex',
                                           'scanIndex',
                                           'rfChannelFrequency',
                                           'numCrcErrors',
                                           'maxRslCrcError',
                                           'numPhyErrors',
                                           'maxRslPhyError',
                                           'maxRslValidFrames',
                                           'channelnumber',
                                           'noiseFloor'],
               'raStatusTable': ['currentTimeSlot',
                                 'raMacAddress',
                                 'raoperationalState',
                                 'unusedTxTimeUL',
                                 'unusedTxTimeDL',
                                 'ancStatus',
                                 'ancHwAvailable'],
               'raTddMacConfigTable': ['passPhrase',
                                       'txPower',
                                       'maxPower',
                                       'maxCrcErrors',
                                       'leakyBucketTimerValue',
                                       'encryptionType'],
               'raTddMacStatisticsTable': ['rxpackets',
                                           'txpackets',
                                           'rxerrors',
                                           'txerrors',
                                           'rxdropped',
                                           'txdropped',
                                           'rxCrcErrors',
                                           'rxPhyError'],
               'raTddMacStatusTable': ['rfChanFreq'],
               'raValidPhyRatesTable': ['mcsindex',
                                        'spatialStreams',
                                        'modulationType',
                                        'codingRate',
                                        'rate'],
               'ruConfTable': ['confIndex',
                               'adminstate',
                               'defaultNodeType',
                               'channelBandwidth',
                               'synchSource',
                               'countryCode',
                               'alignmentControl',
                               'ethFiltering',
                               'poePort2State',
                               'poePort4State',
                               'poePort6State'],
               'ruDateTimeTable': ['dateIndex',
                                   'year',
                                   'month',
                                   'day',
                                   'hour',
                                   'min',
                                   'sec'],
               'ruOmOperationsTable': ['omIndex',
                                       'omOperationReq',
                                       'userName',
                                       'password',
                                       'ftpServerAddress',
                                       'pathName',
                                       'omOperationResult',
                                       'omSpecificCause',
                                       'listOfChannels',
                                       'txTime',
                                       'txRate',
                                       'txBW'],
               'ruStatusTable': ['statusIndex',
                                 'lastRebootReason',
                                 'isConfigCommitedToFlash',
                                 'upTime',
                                 'cpuId',
                                 'ruoperationalState',
                                 'nodeBandwidth',
                                 'poePort2Status',
                                 'poePort4Status',
                                 'poePort6Status'],
               'swStatusTable': ['swStatusIndex',
                                 'activeVersion',
                                 'passiveVersion',
                                 'bootloaderVersion'],
               'syncConfigTable': ['syncConfigIndex',
                                   'adminStatus',
                                   'synchState',
                                   'rasterTime',
                                   'syncLossThreshold',
                                   'leakyBucketTimer',
                                   'syncLostTimeout',
                                   'syncConfigTimerAdjust',
                                   'percentageDownlinkTransmitTime'],
               'synchStatisticsTable': ['syncLostCounter'],
               'synchStatusTable': ['syncoperationalState',
                                    'syncrasterTime',
                                    'timerAdjust',
                                    'syncpercentageDownlinkTransmitTime'],
               'sysOmcRegistrationTable': ['sysOmcRegistrationIndex',
                                           'sysOmcRegisterContactAddr',
                                           'sysOmcRegisterContactPerson',
                                           'sysOmcRegisterContactMobile',
                                           'sysOmcRegisterAlternateContact',
                                           'sysOmcRegisterContactEmail']
    },

    '7.2.29': {'eswATUConfigTable': ['eswATUConfigAtuId',
                                     'eswATUConfigEntryType',
                                     'eswATUConfigPriorityVal',
                                     'eswATUConfigMacAddress',
                                     'eswATUConfigMemberPorts',
                                     'eswATUConfigRowStatus'],
               'eswBadFramesTable': ['eswBadFramesInUndersizeRx',
                                     'eswBadFramesInFragmentsRx',
                                     'eswBadFramesInOversizeRx',
                                     'eswBadFramesInJabberRx',
                                     'eswBadFramesInFCSErrRx',
                                     'eswBadFramesOutFCSErrTx',
                                     'eswBadFramesDeferredTx',
                                     'eswBadFramesCollisionsTx',
                                     'eswBadFramesLateTx',
                                     'eswBadFramesExcessiveTx',
                                     'eswBadFramesSingleTx',
                                     'eswBadFramesMultipleTx'],
               'eswGoodFramesTable': ['eswGoodFramesInUnicast',
                                      'eswGoodFramesOutUnicast',
                                      'eswGoodFramesInBCast',
                                      'eswGoodFramesOutBCast',
                                      'eswGoodFramesInMCast',
                                      'eswGoodFramesOutMcast'],
               'eswMirroringPortTable': ['eswMirroringPort', 'eswMirroringPortSecond'],
               'eswPortAccessListTable': ['eswPortACLSecIndex', 'eswPortACLMacAddress'],
               'eswPortBwTable': ['eswPortBwEgressBw', 'eswPortBwIngressBw'],
               'eswPortConfigTable': ['eswPortConfigPortNum',
                                      'eswPortConfigAdminState',
                                      'eswPortConfigLinkMode',
                                      'eswPortConfigPortVid',
                                      'eswPortConfigAuthState',
                                      'eswPortConfigMirrDir',
                                      'eswPortConfigDotqMode',
                                      'eswPortConfigMacFlowControl'],
               'eswPortQinQTable': ['eswPortQinQAuthState', 'eswPortQinQProviderTag'],
               'eswPortStatisticsTable': ['eswPortStatisticsInDiscards',
                                          'eswPortStatisticsInGoodOctets',
                                          'eswPortStatisticsInBadOctets',
                                          'eswPortStatisticsOutOctets'],
               'eswPortStatusTable': ['eswPortStatusOpState',
                                      'eswPortStatusLinkSpeed',
                                      'eswPortStatusMacFlowControl'],
               'eswVlanConfigTable': ['eswVlanConfigVlanId',
                                      'eswVlanConfigVlanName',
                                      'eswVlanConfigVlanType',
                                      'eswVlanConfigVlanTag',
                                      'eswVlanConfigMemberPorts',
                                      'eswVlanConfigRowStatus'],
               'hwDescTable': ['hwDescIndex', 'hwVersion', 'hwSerialNo'],
               'ipConfigTable': ['ipConfigIndex',
                                 'adminState',
                                 'ipAddress',
                                 'ipNetworkMask',
                                 'ipDefaultGateway',
                                 'autoIpConfig',
                                 'managementMode',
                                 'managementVlanTag'],
               'ipFilterTable': ['ipFilterIndex',
                                 'ipFilterIpAddress',
                                 'ipFilterNetworkMask'],
               'macFilterTable': ['macFilterIndex', 'filterMacAddress'],
               'nwInterfaceStatisticsTable': ['nwStatsIndex',
                                              'rxPackets',
                                              'txPackets',
                                              'rxBytes',
                                              'txBytes',
                                              'rxErrors',
                                              'txErrors',
                                              'rxDropped',
                                              'txDropped'],
               'nwInterfaceStatusTable': ['nwStatusIndex',
                                          'nwInterfaceName',
                                          'operationalState',
                                          'macAddress'],
               'omcConfTable': ['omcConfIndex', 'omcIpAddress', 'periodicStatsTimer'],
               'peerConfigTable': ['timeslotIndex',
                                   'peerMacAddress',
                                   'guaranteedUplinkBW',
                                   'guaranteedDownlinkBW',
                                   'basicRateMCSIndex',
                                   'maxUplinkBW',
                                   'maxDownlinkBW'],
               'peerLinkStatisticsTable': ['timeslotindex',
                                           'txdroped',
                                           'rxDataSubFrames',
                                           'txDataSubFrames',
                                           'signalstrength1',
                                           'txRetransmissions5',
                                           'txRetransmissions4',
                                           'txRetransmissions3',
                                           'txRetransmissions2',
                                           'txRetransmissions1',
                                           'txRetransmissions0',
                                           'rxRetransmissions5',
                                           'rxRetransmissions4',
                                           'rxRetransmissions3',
                                           'rxRetransmissions2',
                                           'rxRetransmissions1',
                                           'rxRetransmissions0',
                                           'rxBroadcastDataSubFrames',
                                           'rateIncreases',
                                           'rateDecreases',
                                           'emptyRasters',
                                           'rxDroppedTpPkts',
                                           'rxDroppedRadioPkts',
                                           'signalstrength2'],
               'peerNodeStatusTable': ['timeSlotIndex',
                                       'linkStatus',
                                       'tunnelStatus',
                                       'sigStrength1',
                                       'peerMacAddr',
                                       'ssIdentifier',
                                       'peerNodeStatusNumSlaves',
                                       'peerNodeStatusrxRate',
                                       'peerNodeStatustxRate',
                                       'allocatedTxBW',
                                       'allocatedRxBW',
                                       'usedTxBW',
                                       'usedRxBW',
                                       'txbasicRate',
                                       'sigStrength2',
                                       'rxbasicRate',
                                       'txLinkQuality',
                                       'peerNodeStatustxTime',
                                       'peerNodeStatusrxTime',
                                       'negotiatedMaxUplinkBW',
                                       'negotiatedMaxDownlinkBW',
                                       'peerNodeStatuslinkDistance'],
               'peerRateStatisticsTable': ['timeSlotindex',
                                           'mcsIndex',
                                           'peerrate',
                                           'per',
                                           'ticks',
                                           'ticksMinimumRateTx',
                                           'ticksWasted'],
               'peerTunnelStatisticsTable': ['tsIndex',
                                             'rxPacket',
                                             'txPacket',
                                             'rxBundles',
                                             'txBundles',
                                             'rxDroped',
                                             'txDroped'],
               'raAclConfigTable': ['aclIndex', 'macaddress', 'rowSts'],
               'raChannelListTable': ['raChanIndex', 'channelNumber', 'frequency'],
               'raConfTable': ['raIndex',
                               'raAdminState',
                               'aclMode',
                               'ssID',
                               'guaranteedBroadcastBW',
                               'dba',
                               'acm',
                               'acs',
                               'dfs',
                               'numSlaves',
                               'antennaPort',
                               'linkDistance',
                               'anc',
                               'forceMimo'],
               'raLlcConfTable': ['arqWinLow',
                                  'arqWinHigh',
                                  'frameLossThreshold',
                                  'leakyBucketTimerVal',
                                  'frameLossTimeout'],
               'raPreferredRFChannelTable': ['preindex', 'preindex', 'rafrequency'],
               'raScanListTable': ['raScanIndex',
                                   'ssid',
                                   'signalStrength',
                                   'macAddr',
                                   'rastertime',
                                   'timeslot',
                                   'maxSlaves',
                                   'channelNum',
                                   'basicRate',
                                   'radfs',
                                   'raacm',
                                   'raanc'],
               'raSiteSurveyResultTable': ['scanIndex',
                                           'scanIndex',
                                           'rfChannelFrequency',
                                           'numCrcErrors',
                                           'maxRslCrcError',
                                           'numPhyErrors',
                                           'maxRslPhyError',
                                           'maxRslValidFrames',
                                           'channelnumber',
                                           'noiseFloor'],
               'raStatusTable': ['currentTimeSlot',
                                 'raMacAddress',
                                 'raoperationalState',
                                 'unusedTxTimeUL',
                                 'unusedTxTimeDL',
                                 'ancStatus',
                                 'ancHwAvailable'],
               'raTddMacConfigTable': ['passPhrase',
                                       'txPower',
                                       'maxPower',
                                       'maxCrcErrors',
                                       'leakyBucketTimerValue',
                                       'encryptionType'],
               'raTddMacStatisticsTable': ['rxpackets',
                                           'txpackets',
                                           'rxerrors',
                                           'txerrors',
                                           'rxdropped',
                                           'txdropped',
                                           'rxCrcErrors',
                                           'rxPhyError'],
               'raTddMacStatusTable': ['rfChanFreq'],
               'raValidPhyRatesTable': ['mcsindex',
                                        'spatialStreams',
                                        'modulationType',
                                        'codingRate',
                                        'rate'],
               'ruConfTable': ['confIndex',
                               'adminstate',
                               'defaultNodeType',
                               'channelBandwidth',
                               'synchSource',
                               'countryCode',
                               'alignmentControl',
                               'ethFiltering',
                               'poePort2State',
                               'poePort4State',
                               'poePort6State'],
               'ruDateTimeTable': ['dateIndex',
                                   'year',
                                   'month',
                                   'day',
                                   'hour',
                                   'min',
                                   'sec'],
               'ruOmOperationsTable': ['omIndex',
                                       'omOperationReq',
                                       'userName',
                                       'password',
                                       'ftpServerAddress',
                                       'pathName',
                                       'omOperationResult',
                                       'omSpecificCause',
                                       'listOfChannels',
                                       'txTime',
                                       'txRate',
                                       'txBW'],
               'ruStatusTable': ['statusIndex',
                                 'lastRebootReason',
                                 'isConfigCommitedToFlash',
                                 'upTime',
                                 'cpuId',
                                 'ruoperationalState',
                                 'nodeBandwidth',
                                 'poePort2Status',
                                 'poePort4Status',
                                 'poePort6Status'],
               'swStatusTable': ['swStatusIndex',
                                 'activeVersion',
                                 'passiveVersion',
                                 'bootloaderVersion'],
               'syncConfigTable': ['syncConfigIndex',
                                   'adminStatus',
                                   'synchState',
                                   'rasterTime',
                                   'syncLossThreshold',
                                   'leakyBucketTimer',
                                   'syncLostTimeout',
                                   'syncConfigTimerAdjust',
                                   'percentageDownlinkTransmitTime'],
               'synchStatisticsTable': ['syncLostCounter'],
               'synchStatusTable': ['syncoperationalState',
                                    'syncrasterTime',
                                    'timerAdjust',
                                    'syncpercentageDownlinkTransmitTime'],
               'sysOmcRegistrationTable': ['sysOmcRegistrationIndex',
                                           'sysOmcRegisterContactAddr',
                                           'sysOmcRegisterContactPerson',
                                           'sysOmcRegisterContactMobile',
                                           'sysOmcRegisterAlternateContact',
                                           'sysOmcRegisterContactEmail']
    },

}
