#!/bin/sh
#chkconfig: 345 99 01
#/etc/init.d/scripts



### BEGIN INIT INFO
# Developer:         Rajendra Sharma and Rahul Gautam
# Provides:          CodeScape Consultants Pvt. Ltd.
# Required-Start:    
# Required-Stop:     
# Default-Start:     
# Default-Stop:      
# Short-Description: Its start to fill the  database tables  
# Description:       First Daemon fill trap alarm database
#		     Second Daemon fill data base trap_alarm_current and trap_alarm_clear according to condition            
# ServiceName:
#
### END INIT INFO

# start-alarm_event, if not disabled in /etc/default/unmp-ds
AUTOSTART=1

PROGNAME=$0


trap="/omd/daemon/trap_alarm.py"
case "$1" in
    start)
	$trap "$1"
    ;;
    stop)
	echo
	$trap "$1"
	echo
    ;;
    restart)
	echo
	$trap "$1"
	echo
    ;;
    help)
	echo
	echo "          *** Unified Network Management Platform ***"
	echo
        echo "  Daemon: 1. Log all events and alarms. 2. Filter the current and clear alarm from all alarm."
	echo
	echo "  Author: Rahul Gauatm "
	echo
	echo "  Provider:  CodeScape Consultants Pvt. Ltd."
	echo
	echo "     Usage: unmp-alarm start | stop | restart | help | status "
	echo
	echo
    ;;
    status)
	echo
	echo " Alarm Status \/ "
	echo
	$trap "$1"
	echo
    ;;
    '')
	echo
	echo "  usage: unmp-alarm start | stop | restart | help |  status "
	echo
	echo " Please use help option if you are using it first time "
	exit 1
    ;;
    *)
	echo
	echo "  usage: unmp-alarm start | stop | restart | help | status "
	echo
	echo " Please use help option if you are using it first time "
	exit 1   

    ;;
esac





