#!/bin/sh
# chkconfig: 345 99 01
#/etc/init.d/scripts



### BEGIN INIT INFO
# Developer:         Yogesh Kumar
# Provides:          CodeScape Consultants Pvt. Ltd.
# Required-Start:    
# Required-Stop:     
# Default-Start:     
# Default-Stop:      
# Short-Description: 
# Description:       
#		     
# ServiceName:
#
### END INIT INFO

# start-alarm_event, if not disabled in /etc/default/unmp-ds
AUTOSTART=1

PROGNAME=$0


trap="/omd/daemon/localhost_monitor.py"
case "$1" in
    start)
	$trap "$1"
    ;;
    stop)
	echo
	$trap "$1"
	echo
    ;;
    restart)
	echo
	$trap "$1"
	echo
    ;;
    help)
	echo
	echo "          *** Unified Network Management Platform ***"
	echo
        echo "  Daemon: Provide localhost States ."
	echo
	echo "  Author: Yogesh Kumar "
	echo
	echo "  Provider:  CodeScape Consultants Pvt. Ltd."
	echo
	echo "     Usage: unmp-local start | stop | restart | help | status "
	echo
	echo
    ;;
    status)
	echo
	echo " Status \/ "
	echo
	$trap "$1"
	echo
    ;;
    '')
	echo
	echo "  usage: unmp-local start | stop | restart | help |  status "
	echo
	echo " Please use help option if you are using it first time "
	exit 1
    ;;
    *)
	echo
	echo "  usage: unmp-local start | stop | restart | help | status "
	echo
	echo " Please use help option if you are using it first time "
	exit 1   

    ;;
esac





