#!/bin/sh
#chkconfig: 345 99 01
#/etc/init.d/scripts

# Startup script to log alarms/trap in database

### BEGIN INIT INFO
# Developer:    Rajendra Sharma
# Provides:     CodeScape Consultants Pvt. Ltd.
# Required-Start:    
# Required-Stop:     
# Default-Start:     
# Default-Stop:      
# Short-Description:  
# Description:  First Daemon fill trap alarm database
#               Second Daemon fill data base trap_alarm_current and trap_alarm_clear according to condition            
# ServiceName:
#
### END INIT INFO

# start-alarm_event, if not disabled in /etc/default/unmp-ds
AUTOSTART=1

PROGNAME=$0

trap="/omd/daemon/trap_alarm.py"
log="/omd/daemon/log/trap_log.log"
case "$1" in
    start)
    	$trap "$1"
    ;;
    stop)
    	$trap "$1"
    ;;
    restart)
    	$trap "$1"
    ;;
    help)
        echo
        echo "          *** Unified Network Management Platform ***"
        echo
        echo "  Daemon: Filter the current and clear alarm from all alarm."
        echo
        echo "  Author: Rajendra Sharma "
        echo
        echo "  Provider:  CodeScape Consultants Pvt. Ltd."
        echo
        echo "     Usage: unmp-alarm start | stop | restart | help | status "
        echo
        echo
    ;;
    status)
	    $trap "$1"
    	exit $?
    ;;
    log)        
	    echo
	    echo "  opening Discovery Server's Log File, Path is  $log  ..."
	    echo "                                                          ............"
        tail -n 30 $log
	    echo 
    ;;
    '')
	echo
	    echo "  usage: unmp-alarm start | stop | restart | help |  status "
	    echo
	    echo " Please use help option if you are using it first time "
	    exit 1
    ;;
    *)
	    echo
	    echo "  usage: unmp-alarm start | stop | restart | help | status "
	    echo
	    echo " Please use help option if you are using it first time "
	    exit 1   
    ;;
esac





