#!/bin/sh
#chkconfig: 345 99 01
# Startup script for Discovery Server

### BEGIN INIT INFO
# Developer:         Rahul Gautam
# Provides:          CodeScape Consultants Pvt. Ltd.
# Required-Start:    
# Required-Stop:     
# Default-Start:     
# Default-Stop:      
# Short-Description: Unicast Discovery Server for different devices (Using TCP Port 6790)
# Description:       Start and stop the sites of the Discovery Server
#
# Acronym:           unmpds := Unified Network Management Platform Discovery Server
# ServiceName:
#
### END INIT INFO

# start unmp-ds, if not disabled in /etc/default/unmp-ds
AUTOSTART=1

PROGNAME=$0
stopds="/omd/daemon/stop-ds"
unmpds="/omd/daemon/unmp-discovery.py"
log="/omd/daemon/log/unmp-discovery.log"
echo "		[34mDiscovery Server[0m"
case "$1" in
    start)
	echo
	$unmpds "$1"
	echo
    ;;
    stop)
	echo
        $unmpds "$1" 
	sleep 3
	$stopds
	echo
    ;;
    restart)
	echo
        $unmpds "$1" 
	echo
    ;;
    help)
	echo
	echo "          *** Unified Network Management Platform ***"
	echo
        echo "  Daemon: Unicast Discovery Server for different devices ( Using TCP Port 6790 )"
	echo
	echo "  Author: Rahul Gautam "
	echo
	echo "  Provider:  CodeScape Consultants Pvt. Ltd."
	echo
	echo "     Usage: unmp-ds start | stop | restart | help | log | status "
	echo
	echo "     use log option to see the Discovery Server's log file "
	echo
    ;;
    status)
	echo
	echo " Discovery Server Status \/ "
	echo
        $unmpds "$1" 
	echo
    ;;
    log)        
	echo
	echo "  opening Discovery Server's Log File, Path is  $log  ..."
	echo "                                                          ............"
        tail -n 30 $log
	echo 
    ;;
    '')
	echo
	echo "  usage: unmp start | stop | restart | help | log | status "
	echo
	echo " Please use help option if you are using it first time "
	exit 1
    ;;
    *)
	echo        
        $unmpds "$1"
	echo
    ;;
esac


