mask_alarm_dict={'CRC_ERROR_THRESHOLD_EXCEEDED': 'CRC_ERROR_THRESHOLD_OK', 'SYNC_LOSS_THRESHOLD_EXCEEDED': 'SYNC_LOSS_THRESHOLD_OK', 'SYNC_LOSS_TIMEOUT': 'SYNC_ACHIEVED'}
mask_severity_dict={}
real_alarm_list=['SYNC_LOSS_THRESHOLD_EXCEEDED', 'SYNC_LOSS_TIMEOUT', 'CRC_ERROR_THRESHOLD_EXCEEDED']