#!/usr/bin/env bash
echo -n "         *Stopping all sub processes "
echo -n "."
a=$( ps -A | grep unmp-discover | awk '{print $1}')
echo -n "."
for i in $a
do 
        echo -n "."
        kill -9 $i
done
echo -n "  [ ok ]"
echo
