#!/bin/sh

cd ..
basedir="${PWD}"
cd bin
# I would prefer it this way, but there does not seem to be a way to
# find out the HOME of the JDK ...
# : ${JAVA_HOME:="@@@JAVA_HOME@@@"}
# ... If there is no JDK, simply set the following ...
# : ${JRE_HOME:="$JAVA_HOME/jre"}

# ... but we have to refer to the JRE only!
: ${JRE_HOME:="/usr/java/jdk1.7.0_01/jre"}

: ${JACORB_HOME:="${basedir}"}

export JACORB_HOME="${basedir}"

: ${JVM_FLAGS:=""}

# call java interpreter
exec ${JRE_HOME}/bin/java ${JVM_FLAGS} \
    -Djava.endorsed.dirs=${JACORB_HOME}/lib -classpath ${JACORB_HOME}/lib/jacorb.jar:${JACORB_HOME}/lib/logkit-1.2.jar:${JACORB_HOME}/lib/avalon-framework-4.1.5.jar:${CLASSPATH} \
    -Djacorb.home=${basedir} \
    -Dorg.omg.CORBA.ORBClass=org.jacorb.orb.ORB \
    -Dorg.omg.CORBA.ORBSingletonClass=org.jacorb.orb.ORBSingleton \
    "$@"

